# Use a Node.js Alpine image for the builder stage
FROM node:22-alpine AS builder

# Define build arguments for environment variables
ARG PRODUCTION_ENVIRONMENT=""
ARG ENVIRONMENT=""
ARG PREVIEW_SECRET=""
ARG UPSTASH_REDIS_REST_TOKEN=""
ARG UPSTASH_REDIS_REST_URL=""
ARG DIRECTUS_REST_URL=""
ARG DIRECTUS_TOKEN=""
ARG DIRECTUS_PREVIEW_TOKEN=""
ARG SITE_ID=""
ARG PUBLIC_SUPPORTED_LANGUAGES=""
ARG CATEGORIES_MAP=""
ARG DATABASE_URL=""
ARG BASE_URL=""
ARG IP_HASH_SALT=""
ARG CF_TURNSTILE_SITE_KEY=""
ARG CF_TURNSTILE_SECRET_KEY=""

# Set environment variables from build arguments
ENV PRODUCTION_ENVIRONMENT=$PRODUCTION_ENVIRONMENT
ENV ENVIRONMENT=$ENVIRONMENT
ENV PREVIEW_SECRET=$PREVIEW_SECRET
ENV UPSTASH_REDIS_REST_TOKEN=$UPSTASH_REDIS_REST_TOKEN
ENV UPSTASH_REDIS_REST_URL=$UPSTASH_REDIS_REST_URL
ENV DIRECTUS_REST_URL=$DIRECTUS_REST_URL
ENV DIRECTUS_TOKEN=$DIRECTUS_TOKEN
ENV DIRECTUS_PREVIEW_TOKEN=$DIRECTUS_PREVIEW_TOKEN
ENV SITE_ID=$SITE_ID
ENV PUBLIC_SUPPORTED_LANGUAGES=$PUBLIC_SUPPORTED_LANGUAGES
ENV CATEGORIES_MAP=$CATEGORIES_MAP
ENV DATABASE_URL=$DATABASE_URL
ENV BASE_URL=$BASE_URL
ENV IP_HASH_SALT=$IP_HASH_SALT
ENV CF_TURNSTILE_SITE_KEY=$CF_TURNSTILE_SITE_KEY
ENV CF_TURNSTILE_SECRET_KEY=$CF_TURNSTILE_SECRET_KEY

# Set Node.js memory and build options to avoid runtime issues
ENV NODE_OPTIONS="--max-old-space-size=4096"
ENV UV_THREADPOOL_SIZE=1

RUN corepack enable pnpm && corepack install -g pnpm@latest
WORKDIR /app
COPY package*.json ./
RUN pnpm install
COPY . .
RUN pnpm build
RUN pnpm prune --production

ENV PRODUCTION_ENVIRONMENT=$PRODUCTION_ENVIRONMENT
ENV ENVIRONMENT=$ENVIRONMENT
ENV PREVIEW_SECRET=$PREVIEW_SECRET
ENV UPSTASH_REDIS_REST_TOKEN=$UPSTASH_REDIS_REST_TOKEN
ENV UPSTASH_REDIS_REST_URL=$UPSTASH_REDIS_REST_URL
ENV DIRECTUS_REST_URL=$DIRECTUS_REST_URL
ENV DIRECTUS_TOKEN=$DIRECTUS_TOKEN
ENV DIRECTUS_PREVIEW_TOKEN=$DIRECTUS_PREVIEW_TOKEN
ENV SITE_ID=$SITE_ID
ENV PUBLIC_SUPPORTED_LANGUAGES=$PUBLIC_SUPPORTED_LANGUAGES
ENV CATEGORIES_MAP=$CATEGORIES_MAP
ENV DATABASE_URL=$DATABASE_URL
ENV BASE_URL=$BASE_URL
ENV IP_HASH_SALT=$IP_HASH_SALT
ENV CF_TURNSTILE_SITE_KEY=$CF_TURNSTILE_SITE_KEY
ENV CF_TURNSTILE_SECRET_KEY=$CF_TURNSTILE_SECRET_KEY

# Use another Node.js Alpine image for the final stage
FROM node:22-alpine
WORKDIR /app
COPY --from=builder /app/build build/
COPY --from=builder /app/node_modules node_modules/
COPY package.json .
EXPOSE 80
ENV NODE_ENV=production
CMD [ "node", "build" ]