const MAX_COOKIE_EXPIRATION_TIME = 60 * 60 * 24 * 30 * 24//62208000

const SESSION_COOKIE_EXPIRATION_TIME = 60 * 60 * 7 + 60 * 55 //28500

const SESSION_COOKIE_SERIALIZATION = { path: '/', httpOnly: true, secure: true, sameSite: 'strict', maxAge: SESSION_COOKIE_EXPIRATION_TIME } as const

const MAX_COOKIE_SERIALIZATION = { ...SESSION_COOKIE_SERIALIZATION, maxAge: MAX_COOKIE_EXPIRATION_TIME } as const

export {
  SESSION_COOKIE_SERIALIZATION,
  MAX_COOKIE_SERIALIZATION
}