name: Deploy to Development

on:
  #push:
    #branches:
    #  - feature/container-app
  workflow_dispatch:
  push:
  
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/common-deploy.yml
    secrets: inherit
    with:
      environment: development
      env: dev
      environment_url: https://panamav2-dev-cdn.d6nfe7i1.monks.zone
      aws_role: arn:aws:iam::637423230985:role/github-actions-dev
      production_flag: ""
      build_environment: production
